# Generated by Django 3.1.7 on 2021-04-04 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.ImageField(upload_to='song/cover')),
                ('name', models.CharField(max_length=255)),
                ('feat', models.CharField(max_length=255)),
            ],
        ),
    ]
