# Generated by Django 3.1.7 on 2021-04-04 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='song/cover'),
        ),
        migrations.AlterField(
            model_name='song',
            name='feat',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
