# Generated by Django 3.1.7 on 2021-04-06 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_song_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='song',
            field=models.FileField(default=0, upload_to='song/song'),
            preserve_default=False,
        ),
    ]
