# Generated by Django 3.1.7 on 2021-04-04 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_auto_20210404_1649'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='name',
            new_name='title',
        ),
    ]
